const overviewItems = [
  {
    id: 1,
    name: "value",
    title: "Portfolio Value",
    content: (h) => h.balance * h.closePrice,
    currencyItem: true,
    agregateType: "sum",
  },
  {
    id: 2,
    name: "gains",
    title: "Total Realized Gain",
    content: (h) => h.realizedGain,
    currencyItem: true,
    agregateType: "sum",
  },
  {
    id: 3,
    name: "fees",
    title: "Total Fees Paid",
    content: (h) => h.accruedFees,
    currencyItem: true,
    agregateType: "sum",
  },
  {
    id: 4,
    name: "positions",
    title: "Total Positions Open",
    content: (h) => h.balance !== 0,
    currencyItem: false,
    agregateType: "count",
  },
  {
    id: 5,
    name: "positions",
    title: "Total Positions Closed",
    content: (h) => h.balance === 0,
    currencyItem: false,
    agregateType: "count",
  },
  {
    id: 6,
    name: "tradeDate",
    title: "Last Trade",
    content: (h) => h.tradeDate,
    parameter: "tradeDate",
    dateItem: true,
    agregateType: "largest",
    direction: 1,
  },
  {
    id: 7,
    name: "largestPosistion",
    title: "Largest Position",
    content: (h) => h.balance * h.closePrice,
    parameter: "symbol",
    currencyItem: false,
    agregateType: "largest",
    direction: 1,
  },
  {
    id: 8,
    name: "smallestPosistion",
    title: "Smallest Position",
    content: (h) => h.balance * h.closePrice,
    parameter: "symbol",
    currencyItem: false,
    agregateType: "largest",
    direction: -1,
  },
];

export default overviewItems;
